In [2]:
import pandas as pd

df_test = pd.read_excel(
    r"C:\Users\Manasa A\Downloads\online+retail\Online Retail.xlsx",
    nrows=5,
    engine="openpyxl"
)

df_test

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [3]:
df_test.shape

(5, 8)

In [4]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    5 non-null      int64
 1   StockCode    5 non-null      object
 2   Description  5 non-null      object
 3   Quantity     5 non-null      int64
 4   InvoiceDate  5 non-null      datetime64[ns]
 5   UnitPrice    5 non-null      float64
 6   CustomerID   5 non-null      int64
 7   Country      5 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(3), object(3)
memory usage: 452.0+ bytes

In [5]:
df = pd.read_excel(
    r"C:\Users\Manasa A\Downloads\online+retail\Online Retail.xlsx",
    engine="openpyxl"
)

In [6]:
df.shape

(541909, 8)

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [8]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [9]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(5268)

In [11]:
df['InvoiceNo'].astype(str).str.startswith('C').sum()

np.int64(9288)

In [12]:
df['Quantity'].describe()

count    541909.000000
mean          9.552250
std         218.081158
min      -80995.000000
25%           1.000000
50%           3.000000
75%          10.000000
max       80995.000000
Name: Quantity, dtype: float64

In [13]:
(df['Quantity'] < 0).sum()

np.int64(10624)

In [14]:
(df['Quantity'] == 0).sum()

np.int64(0)

In [15]:
df['UnitPrice'].describe()

count    541909.000000
mean          4.611114
std          96.759853
min      -11062.060000
25%           1.250000
50%           2.080000
75%           4.130000
max       38970.000000
Name: UnitPrice, dtype: float64

In [16]:
(df['UnitPrice'] <= 0).sum()

np.int64(2517)

In [17]:
df[df['UnitPrice'] <= 0][['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'UnitPrice', 'CustomerID']].head(10)

     InvoiceNo StockCode Description  Quantity  UnitPrice  CustomerID
622     536414     22139         NaN        56        0.0         NaN
1970    536545     21134         NaN         1        0.0         NaN
1971    536546     22145         NaN         1        0.0         NaN
1972    536547     37509         NaN         1        0.0         NaN
1987    536549    85226A         NaN         1        0.0         NaN
1988    536550     85044         NaN         1        0.0         NaN
2024    536552     20950         NaN         1        0.0         NaN
2025    536553     37461         NaN         3        0.0         NaN
2026    536554     84670         NaN        23        0.0         NaN
2406    536589     21777         NaN       -10        0.0         NaN

In [18]:
df[df['UnitPrice'] <= 0]['UnitPrice'].value_counts().sort_index()

UnitPrice
-11062.06       2
 0.00        2515
Name: count, dtype: int64

In [19]:
df['StockCode'].value_counts().head(20)

StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
84879     1502
22720     1477
22197     1476
21212     1385
20727     1350
22383     1348
22457     1280
23203     1267
POST      1256
22386     1251
22469     1239
22960     1229
21931     1214
22086     1210
22411     1202
Name: count, dtype: int64

In [20]:
df['InvoiceNo'].astype(str).str.startswith('C').value_counts()

InvoiceNo
False    532621
True       9288
Name: count, dtype: int64

In [21]:
df['CustomerID'].nunique()

4372

In [22]:
df['InvoiceDate'].min(), df['InvoiceDate'].max()

(Timestamp('2010-12-01 08:26:00'), Timestamp('2011-12-09 12:50:00'))

In [23]:
df_clean = df.copy()

In [24]:
df_clean.shape

(541909, 8)

df_clean = df_clean.drop_duplicates()

In [26]:
df_clean.shape

(541909, 8)

In [27]:
df_clean.duplicated().sum()

np.int64(5268)

In [28]:
df_clean = df_clean.drop_duplicates()

print("Shape:", df_clean.shape)
print("Duplicates:", df_clean.duplicated().sum())

Shape: (536641, 8)
Duplicates: 0

In [29]:
df_clean = df_clean[df_clean['UnitPrice'] > 0]

In [30]:
print("Shape:", df_clean.shape)
print("Invalid UnitPrice:", (df_clean['UnitPrice'] <= 0).sum())

Shape: (534129, 8)
Invalid UnitPrice: 0

In [31]:
df_clean[df_clean['Quantity'] < 0]['InvoiceNo'].astype(str).str.startswith('C').value_counts()

InvoiceNo
True    9251
Name: count, dtype: int64

In [32]:
df_clean[
    (df_clean['Quantity'] < 0) &
    (~df_clean['InvoiceNo'].astype(str).str.startswith('C'))
][['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'UnitPrice', 'CustomerID']].head(10)

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, UnitPrice, CustomerID]
Index: []

In [33]:
print("Negative quantity rows:", (df_clean['Quantity'] < 0).sum())

print(
    "Negative quantity + non-C invoice:",
    (
        (df_clean['Quantity'] < 0) &
        (~df_clean['InvoiceNo'].astype(str).str.startswith('C'))
    ).sum()
)

Negative quantity rows: 9251
Negative quantity + non-C invoice: 0

In [34]:
df_sales = df_clean[df_clean['Quantity'] > 0].copy()

df_returns = df_clean[df_clean['Quantity'] < 0].copy()

In [35]:
print("Sales:", df_sales.shape)
print("Returns:", df_returns.shape)

Sales: (524878, 8)
Returns: (9251, 8)

In [36]:
df_sales['CustomerID'].isnull().sum()

np.int64(132186)

In [37]:
df_customer = df_sales.dropna(subset=['CustomerID']).copy()

In [38]:
print("Customer analysis rows:", df_customer.shape)
print("Missing CustomerID:", df_customer['CustomerID'].isnull().sum())

Customer analysis rows: (392692, 8)
Missing CustomerID: 0

In [39]:
df_customer['CustomerID'] = df_customer['CustomerID'].astype(int)

In [40]:
df_customer['CustomerID'].dtype

dtype('int64')

In [41]:
df_sales['Description'].isnull().sum()

np.int64(0)

In [42]:
print("Quantity <= 0:", (df_sales['Quantity'] <= 0).sum())
print("UnitPrice <= 0:", (df_sales['UnitPrice'] <= 0).sum())

Quantity <= 0: 0
UnitPrice <= 0: 0

In [43]:
df_sales['Revenue'] = df_sales['Quantity'] * df_sales['UnitPrice']

In [44]:
df_sales[['Quantity', 'UnitPrice', 'Revenue']].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

In [45]:
print("Revenue <= 0:", (df_sales['Revenue'] <= 0).sum())

Revenue <= 0: 0

In [46]:
total_revenue = df_sales['Revenue'].sum()
total_revenue

np.float64(10642110.804000001)

In [47]:
total_quantity = df_sales['Quantity'].sum()
total_quantity

np.int64(5572420)

In [48]:
total_orders = df_sales['InvoiceNo'].nunique()
total_orders

19960

In [49]:
average_order_value = total_revenue / total_orders
average_order_value

np.float64(533.171883967936)

In [50]:
total_customers = df_customer['CustomerID'].nunique()
total_customers

4338

In [51]:
revenue_per_customer = total_revenue / total_customers
revenue_per_customer

np.float64(2453.2297842323655)

In [52]:
country_revenue = (
    df_sales.groupby('Country')['Revenue']
    .sum()
    .sort_values(ascending=False)
)

country_revenue.head(10)

Country
United Kingdom    9001744.094
Netherlands        285446.340
EIRE               283140.520
Germany            228678.400
France             209625.370
Australia          138453.810
Spain               61558.560
Switzerland         57067.600
Belgium             41196.340
Sweden              38367.830
Name: Revenue, dtype: float64

In [53]:
monthly_revenue = (
    df_sales.groupby(df_sales['InvoiceDate'].dt.to_period('M'))['Revenue']
    .sum()
)

monthly_revenue

InvoiceDate
2010-12     821452.730
2011-01     689811.610
2011-02     522545.560
2011-03     716215.260
2011-04     536968.491
2011-05     769296.610
2011-06     760547.010
2011-07     718076.121
2011-08     757841.380
2011-09    1056435.192
2011-10    1151263.730
2011-11    1503866.780
2011-12     637790.330
Freq: M, Name: Revenue, dtype: float64

In [54]:
monthly_orders = (
    df_sales.groupby(df_sales['InvoiceDate'].dt.to_period('M'))['InvoiceNo']
    .nunique()
)

monthly_orders

InvoiceDate
2010-12    1559
2011-01    1086
2011-02    1100
2011-03    1454
2011-04    1246
2011-05    1681
2011-06    1533
2011-07    1475
2011-08    1361
2011-09    1837
2011-10    2040
2011-11    2769
2011-12     819
Freq: M, Name: InvoiceNo, dtype: int64

In [55]:
product_revenue = (
    df_sales.groupby('Description')['Revenue']
    .sum()
    .sort_values(ascending=False)
)

product_revenue.head(10)

Description
DOTCOM POSTAGE                        206248.77
REGENCY CAKESTAND 3 TIER              174156.54
PAPER CRAFT , LITTLE BIRDIE           168469.60
WHITE HANGING HEART T-LIGHT HOLDER    106236.72
PARTY BUNTING                          99445.23
JUMBO BAG RED RETROSPOT                94159.81
MEDIUM CERAMIC TOP STORAGE JAR         81700.92
POSTAGE                                78101.88
Manual                                 77752.82
RABBIT NIGHT LIGHT                     66870.03
Name: Revenue, dtype: float64

In [56]:
exclude_products = ['DOTCOM POSTAGE', 'POSTAGE', 'Manual']

product_revenue_clean = (
    df_sales[~df_sales['Description'].isin(exclude_products)]
    .groupby('Description')['Revenue']
    .sum()
    .sort_values(ascending=False)
)

product_revenue_clean.head(10)

Description
REGENCY CAKESTAND 3 TIER              174156.54
PAPER CRAFT , LITTLE BIRDIE           168469.60
WHITE HANGING HEART T-LIGHT HOLDER    106236.72
PARTY BUNTING                          99445.23
JUMBO BAG RED RETROSPOT                94159.81
MEDIUM CERAMIC TOP STORAGE JAR         81700.92
RABBIT NIGHT LIGHT                     66870.03
PAPER CHAIN KIT 50'S CHRISTMAS         64875.59
ASSORTED COLOUR BIRD ORNAMENT          58927.62
CHILLI LIGHTS                          54096.36
Name: Revenue, dtype: float64

In [57]:
product_quantity = (
    df_sales[~df_sales['Description'].isin(exclude_products)]
    .groupby('Description')['Quantity']
    .sum()
    .sort_values(ascending=False)
)

product_quantity.head(10)

Description
PAPER CRAFT , LITTLE BIRDIE           80995
MEDIUM CERAMIC TOP STORAGE JAR        78033
WORLD WAR 2 GLIDERS ASSTD DESIGNS     54951
JUMBO BAG RED RETROSPOT               48371
WHITE HANGING HEART T-LIGHT HOLDER    37872
POPCORN HOLDER                        36749
PACK OF 72 RETROSPOT CAKE CASES       36396
ASSORTED COLOUR BIRD ORNAMENT         36362
RABBIT NIGHT LIGHT                    30739
MINI PAINT SET VINTAGE                26633
Name: Quantity, dtype: int64

In [58]:
top_quantity_products = product_quantity.head(10).index

top_quantity_price = (
    df_sales[df_sales['Description'].isin(top_quantity_products)]
    .groupby('Description')['UnitPrice']
    .mean()
    .sort_values(ascending=False)
)

top_quantity_price

Description
WHITE HANGING HEART T-LIGHT HOLDER    3.218334
JUMBO BAG RED RETROSPOT               2.486197
RABBIT NIGHT LIGHT                    2.386401
PAPER CRAFT , LITTLE BIRDIE           2.080000
ASSORTED COLOUR BIRD ORNAMENT         1.722575
MEDIUM CERAMIC TOP STORAGE JAR        1.468480
POPCORN HOLDER                        1.020836
MINI PAINT SET VINTAGE                0.785026
PACK OF 72 RETROSPOT CAKE CASES       0.761206
WORLD WAR 2 GLIDERS ASSTD DESIGNS     0.320728
Name: UnitPrice, dtype: float64

In [60]:
df_customer['Revenue'] = df_customer['Quantity'] * df_customer['UnitPrice']

In [61]:
customer_revenue = (
    df_customer.groupby('CustomerID')['Revenue']
    .sum()
    .sort_values(ascending=False)
)

customer_revenue.head(10)

CustomerID
14646    280206.02
18102    259657.30
17450    194390.79
16446    168472.50
14911    143711.17
12415    124914.53
14156    117210.08
17511     91062.38
16029     80850.84
12346     77183.60
Name: Revenue, dtype: float64

In [62]:
customer_orders = (
    df_customer.groupby('CustomerID')['InvoiceNo']
    .nunique()
    .sort_values(ascending=False)
)

customer_orders.head(10)

CustomerID
12748    209
14911    201
17841    124
13089     97
14606     93
15311     91
12971     86
14646     73
16029     63
13408     62
Name: InvoiceNo, dtype: int64

In [63]:
customer_aov = (
    df_customer.groupby('CustomerID')['Revenue'].sum()
    / df_customer.groupby('CustomerID')['InvoiceNo'].nunique()
)

customer_aov.sort_values(ascending=False).head(10)

CustomerID
16446    84236.250000
12346    77183.600000
15749    14844.766667
15098    13305.500000
12357     6207.670000
12415     5948.310952
12590     4932.130000
12688     4873.810000
12752     4366.780000
18102     4327.621667
dtype: float64

In [64]:
rfm = df_customer.groupby('CustomerID').agg(
    LastPurchaseDate=('InvoiceDate', 'max'),
    Frequency=('InvoiceNo', 'nunique'),
    Monetary=('Revenue', 'sum')
)

rfm.head()

              LastPurchaseDate  Frequency  Monetary
CustomerID
12346      2011-01-18 10:01:00          1  77183.60
12347      2011-12-07 15:52:00          7   4310.00
12348      2011-09-25 13:13:00          4   1797.24
12349      2011-11-21 09:51:00          1   1757.55
12350      2011-02-02 16:01:00          1    334.40

In [65]:
reference_date = df_customer['InvoiceDate'].max() + pd.Timedelta(days=1)

rfm['Recency'] = (
    reference_date - rfm['LastPurchaseDate']
).dt.days

rfm.head()

              LastPurchaseDate  Frequency  Monetary  Recency
CustomerID
12346      2011-01-18 10:01:00          1  77183.60      326
12347      2011-12-07 15:52:00          7   4310.00        2
12348      2011-09-25 13:13:00          4   1797.24       75
12349      2011-11-21 09:51:00          1   1757.55       19
12350      2011-02-02 16:01:00          1    334.40      310

In [66]:
rfm[['Recency', 'Frequency', 'Monetary']].describe()

           Recency    Frequency       Monetary
count  4338.000000  4338.000000    4338.000000
mean     92.536422     4.272015    2048.688081
std     100.014169     7.697998    8985.230220
min       1.000000     1.000000       3.750000
25%      18.000000     1.000000     306.482500
50%      51.000000     2.000000     668.570000
75%     142.000000     5.000000    1660.597500
max     374.000000   209.000000  280206.020000

In [68]:
rfm['R_Score'] = pd.qcut(
    rfm['Recency'].rank(method='first'),
    5,
    labels=[5, 4, 3, 2, 1]
).astype(int)

rfm['F_Score'] = pd.qcut(
    rfm['Frequency'].rank(method='first'),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

rfm['M_Score'] = pd.qcut(
    rfm['Monetary'].rank(method='first'),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

rfm.head()

,LastPurchaseDate,Frequency,Monetary,Recency,R_Score,F_Score,M_Score
CustomerID,,,,,,,
12346,2011-01-18 10:01:00,1,77183.60,326,1,1,5
12347,2011-12-07 15:52:00,7,4310.00,2,5,5,5
12348,2011-09-25 13:13:00,4,1797.24,75,2,4,4
12349,2011-11-21 09:51:00,1,1757.55,19,4,1,4
12350,2011-02-02 16:01:00,1,334.40,310,1,1,2

In [69]:
rfm['RFM_Score'] = (
    rfm['R_Score'] +
    rfm['F_Score'] +
    rfm['M_Score']
)

rfm[['Recency', 'Frequency', 'Monetary',
     'R_Score', 'F_Score', 'M_Score', 'RFM_Score']].head(10)

            Recency  Frequency  Monetary  R_Score  F_Score  M_Score  RFM_Score
CustomerID
12346           326          1  77183.60        1        1        5          7
12347             2          7   4310.00        5        5        5         15
12348            75          4   1797.24        2        4        4         10
12349            19          1   1757.55        4        1        4          9
12350           310          1    334.40        1        1        2          4
12352            36          8   2506.04        3        5        5         13
12353           204          1     89.00        1        1        1          3
12354           232          1   1079.40        1        1        4          6
12355           214          1    459.40        1        1        2          4
12356            23          3   2811.43        4        3        5         12

In [70]:
rfm['RFM_Score'].value_counts().sort_index()

RFM_Score
3     184
4     363
5     338
6     427
7     381
8     380
9     324
10    349
11    349
12    314
13    287
14    295
15    347
Name: count, dtype: int64

In [71]:
def rfm_segment(score):
    if score >= 13:
        return 'Champions'
    elif score >= 10:
        return 'Loyal / Potential Loyalists'
    elif score >= 7:
        return 'Needs Attention'
    elif score >= 4:
        return 'At Risk'
    else:
        return 'Lost'


rfm['Segment'] = rfm['RFM_Score'].apply(rfm_segment)

rfm[['RFM_Score', 'Segment']].head(10)

            RFM_Score                      Segment
CustomerID
12346               7              Needs Attention
12347              15                    Champions
12348              10  Loyal / Potential Loyalists
12349               9              Needs Attention
12350               4                      At Risk
12352              13                    Champions
12353               3                         Lost
12354               6                      At Risk
12355               4                      At Risk
12356              12  Loyal / Potential Loyalists

In [72]:
segment_counts = (
    rfm['Segment']
    .value_counts()
)

segment_counts

Segment
At Risk                        1128
Needs Attention                1085
Loyal / Potential Loyalists    1012
Champions                       929
Lost                            184
Name: count, dtype: int64

In [73]:
segment_revenue = (
    rfm.groupby('Segment')['Monetary']
    .sum()
    .sort_values(ascending=False)
)

segment_revenue

Segment
Champions                      6229304.440
Loyal / Potential Loyalists    1412579.341
Needs Attention                 878587.722
At Risk                         340138.981
Lost                             26598.410
Name: Monetary, dtype: float64

In [74]:
segment_revenue_pct = (
    segment_revenue / segment_revenue.sum() * 100
).round(2)

segment_revenue_pct

Segment
Champions                      70.09
Loyal / Potential Loyalists    15.89
Needs Attention                 9.89
At Risk                         3.83
Lost                            0.30
Name: Monetary, dtype: float64

In [75]:
customer_country = (
    df_customer.groupby('Country')['CustomerID']
    .nunique()
    .sort_values(ascending=False)
)

customer_country.head(10)

Country
United Kingdom    3920
Germany             94
France              87
Spain               30
Belgium             25
Switzerland         21
Portugal            19
Italy               14
Finland             12
Austria             11
Name: CustomerID, dtype: int64

In [76]:
country_customer_value = (
    df_customer.groupby('Country')['Revenue']
    .sum()
    / df_customer.groupby('Country')['CustomerID'].nunique()
)

country_customer_value.sort_values(ascending=False).head(10)

Country
EIRE           88420.820000
Netherlands    31716.260000
Singapore      21279.290000
Australia      15383.756667
Sweden          4795.978750
Japan           4677.046250
Iceland         4310.000000
Norway          3616.544000
Switzerland     2687.807143
Germany         2432.748936
dtype: float64

In [77]:
df_returns

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [78]:
return_revenue = (
    df_returns['Quantity'] * df_returns['UnitPrice']
).sum()

return_units = df_returns['Quantity'].abs().sum()

print("Return value:", return_revenue)
print("Returned units:", return_units)

Return value: -893979.73
Returned units: 275560

In [79]:
return_rate_units = (
    return_units / total_quantity * 100
)

print("Return rate by units:", round(return_rate_units, 2), "%")

Return rate by units: 4.95 %

In [80]:
return_products = (
    df_returns.groupby('Description')['Quantity']
    .sum()
    .abs()
    .sort_values(ascending=False)
)

return_products.head(10)

Description
PAPER CRAFT , LITTLE BIRDIE            80995
MEDIUM CERAMIC TOP STORAGE JAR         74494
ROTATING SILVER ANGELS T-LIGHT HLDR     9376
Manual                                  4066
FAIRY CAKE FLANNEL ASSORTED COLOUR      3150
WHITE HANGING HEART T-LIGHT HOLDER      2578
GIN + TONIC DIET METAL SIGN             2030
HERB MARKER BASIL                       1527
FELTCRAFT DOLL MOLLY                    1447
TEA TIME PARTY BUNTING                  1424
Name: Quantity, dtype: int64

In [81]:
product_sales = (
    df_sales.groupby('Description')['Quantity']
    .sum()
)

product_returns = (
    df_returns.groupby('Description')['Quantity']
    .sum()
    .abs()
)

product_return_rate = (
    product_returns / product_sales * 100
).sort_values(ascending=False)

product_return_rate.head(15)

Description
SAMPLES                                3000.000000
AMAZON FEE                             1600.000000
BLUE PADDED SOFT MOBILE                 700.000000
PINK POODLE HANGING DECORATION          240.000000
Bank Charges                            208.333333
PINK CHERRY LIGHTS                      200.000000
WOODEN BOX ADVENT CALENDAR              160.000000
3 WICK CHRISTMAS BRIAR CANDLE           133.333333
ROBIN CHRISTMAS CARD                    120.000000
PINK SMALL GLASS CAKE STAND             112.500000
GLASS CAKE COVER AND PLATE              100.000000
BLACK CHERRY LIGHTS                     100.000000
HANGING RIDGE GLASS T-LIGHT HOLDER      100.000000
WHITE BEADED GARLAND STRING 20LIGHT     100.000000
PAPER CRAFT , LITTLE BIRDIE             100.000000
Name: Quantity, dtype: float64

In [82]:
exclude_non_products = [
    'Manual',
    'POSTAGE',
    'DOTCOM POSTAGE',
    'AMAZON FEE',
    'Bank Charges',
    'SAMPLES'
]

clean_return_products = (
    df_returns[
        ~df_returns['Description'].isin(exclude_non_products)
    ]
    .groupby('Description')['Quantity']
    .sum()
    .abs()
    .sort_values(ascending=False)
)

clean_return_products.head(10)

Description
PAPER CRAFT , LITTLE BIRDIE            80995
MEDIUM CERAMIC TOP STORAGE JAR         74494
ROTATING SILVER ANGELS T-LIGHT HLDR     9376
FAIRY CAKE FLANNEL ASSORTED COLOUR      3150
WHITE HANGING HEART T-LIGHT HOLDER      2578
GIN + TONIC DIET METAL SIGN             2030
HERB MARKER BASIL                       1527
FELTCRAFT DOLL MOLLY                    1447
TEA TIME PARTY BUNTING                  1424
PAPER POCKET TRAVELING FAN              1385
Name: Quantity, dtype: int64

In [83]:
df_sales.to_csv(
    r"C:\Users\Manasa A\Downloads\ecommerce_sales_cleaned.csv",
    index=False
)

In [84]:
print("CSV created successfully!")
print(df_sales.shape)

CSV created successfully!
(524878, 9)